# Site settings
title: FanSte | Blog
url: "http://fanst3.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "/" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
timezone: Europe/Belgrade
description: >
  One or more sentences introducing this blog.

# Your information
email: jovisicstefan73@gmail.com
author: FanSte
avatar: "//cdn.discordapp.com/attachments/1041408358248366212/1241543288708661259/IMG_4888.png?ex=664a94ca&is=6649434a&hm=c6442dbf75d1f954fd6b1cb630f725b63747718d7e070b06e1bb10d61bb26570&"
profile: Serbia, 17yo, interested in web security.
profile_links:
  Email: "mailto:jovisicstefan73@gmail.com"
  GitHub: "https://github.com/FanSt3"
  Instagram: "https://instagram.com/stefke.j"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    Home: /
    About: /about/
    #Category: /category/
    #Donate: https://laobubu.net/donate.html

permalink: /posts/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
